
--create the AuditLog table:


CREATE TABLE AuditLog (
  LogID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  TransactionID NUMBER,
  Action VARCHAR2(20),
  LogDate DATE
);


-- Trigger to log every new transaction insert into AuditLog

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
  INSERT INTO AuditLog (TransactionID, Action, LogDate)
  VALUES (:NEW.TransactionID, 'INSERT', SYSDATE);
END;
/
